### PR TITLE
Marks branch

### PR DESCRIPTION
**Pull request by fordmadox**
No need to merge if you don't want the extra javascript file, but I added that so I could use keyboard shortcuts during testing.  The right arrow key now triggers the next link; the left arrow key triggers the previous link; and the "h" and "s" keys trigger the return to start link.  I also made a few other minor changes to the HTML files, but I haven't gotten past slide 29 yet.  

By the way, so far this is a great introduction to the ASpace API and Python!!!

### CODE REVIEW

**Comment by rsdoiel** [comment]
Thank you!  I've been plugging away on this end with the writing and tweaks to make the read/writing process for me easier.  I think login and repositories are close. Working through Agents now (probably just focus on people and hand wave for the other other types). I'll probably wrap up the coding with Accessions then we can discuss how it might be extended for things like Digital Objects and so on.  With any luck participant will feel empowered to really harness the API.

Oh, you have a preferred syntax highlighter for Python send me a link and I will add it to the template.

All the best,

Robert

**Comment by rsdoiel** [comment]
Oh, one more thing while I am thinking of it. The slides are defined in slides.template. The little md2slides program I wrote uses that to generate all the individual slides.  Sorry forgot to mention that. Save you going through a zillion slides by hand.  All the best,

Should have your keyboard commands merged in in a minute.

Robert

**Comment by rsdoiel** [comment]
Ok, I've updated the template, made a couple small changes to the JavaScript and put it in a folder called js rather than scripts (so it doesn't get confused with Python code if some goes looking).

**Comment by fordmadox** [comment]
Thanks!  Yes, I was going to use id attributes originally for the trigger, but then I didn't want to add those attributes to all of the links, so I went with the title attribute.  But this is much more clean, so thanks for updating that file. Also, since I didn't notice there was a template, I just added the JS file to the HTML headers with a single find and replace in a text editor :)

**Comment by rsdoiel** [comment]
A good editor is always nice.  I working through agents now. Hopefully finish those today and get on to accessions next.  I think repositories is almost OK. If all goes as plan (does it every?) then mid week I just be doing copy editing, fixing/improving prose, etc.

**Pull request closed without merging**
